# Workflow name
name: 'Chromatic Publish'

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10 # docs https://pnpm.io/continuous-integration#github-actions
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      #👇 Adds Chromatic as a step in the workflow
      - name: Run Chromatic
        uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken,
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
