name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: 'Publish to npm registry'
        run: |
          npm ci --legacy-peer-deps
          npm run build
          git config --global user.email "55526292+daqichen@users.noreply.github.com" && git config --global user.name "daqichen"
          npm version patch
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
